
DROP TABLE BOARD;

CREATE TABLE BOARD
(
	BOARDNO VARCHAR2(20) PRIMARY KEY,
	BOARDTITLE VARCHAR2(20),
	BOARDWRITER VARCHAR2(20),
	BOARDCONTENT VARCHAR2(2000),
	BOARDDATE DATE
);




DROP SEQUENCE BOARD_SEQ;



CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'자소서','박용운','안녕하우한우하ㅣㄴ우한우히ㅏㄴ',SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'자소서1','박용운','안녕ㄴㅇㅁㅇ하우한우하ㅣㄴ우한우히ㅏㄴ',SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'자소서2','박용운','안녕하우한우ㅁㄴㅇㄻㄴㄹ하ㅣㄴ우한우히ㅏㄴ',SYSDATE);


